version: "3.7"

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - 8080:8080
    environment:
      AUTH_TYPE: $KAFKA_UI_AUTH_TYPE
      SPRING_SECURITY_USER_NAME: $KAFKA_UI_USER_NAME
      SPRING_SECURITY_USER_PASSWORD: $KAFKA_UI_PASSWORD
      KAFKA_CLUSTERS_0_NAME: Falser
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9101
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect-falser
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
      KAFKA_CLUSTERS_0_KSQLDBSERVER: http://ksqldb-server:8088
    networks:
      - falser-kafka-ui-network

networks:
  falser-kafka-ui-network:
    name: falser-network
